### ISSUE TITLE
TypeError: Cannot call a class as a function for TrendChart

### ISSUE THREAD

**Issue by satyajituk** [pmkroeker/preact-charts#20]
I am trying to implement the example given [here](https://codesandbox.io/s/ko300qzppv) in my project. 

But I get the error : `TypeError: Cannot call a class as a function` for `TrendChart` even though I have put the same way as the example. So not sure whats wrong.

**Comment by pmkroeker** [comment]
Hmm, are you able to reproduce the issue in a [sandbox](https://codesandbox.io/)?

Also which version of both `preact-charts` and `preact` are you using? Currently using `preact-charts@next` will work for both `preact@8.4.2` and `preact@10.0.0-beta.1`. So upgrading may be an option. Its probably time that I updated the demo anyways, so I'll update it using more recent versions and see if that replicates the issue.

**Comment by pmkroeker** [comment]
I'm going to close this issue for inactivity, and being unable to reproduce the problem. If this occurs again or more information is provided it can be re-opened.
